### PR TITLE
Feature/LLOQ

### PR DESCRIPTION
**Pull request by FelicienLL**
## Summary

The objective of this PR is to set up the M3 method in order to analyse data below the lower limit of quantification. 
So far so good, the example provided by @pchelle in #163 works fine.

## To do
- Safety checks
- Option to pass LLOQ to mapbayest
- Validate vs nonmem on simulated data set maybe (think about)

### CODE REVIEW

**Comment by pchelle** [comment]
@FelicienLL 
Thanks so much for working on this !
I was actually thinking of making the method more generic with a likelihood flag 
Something like:
```r
ofv_likelihood <- function(pred){
sum(-2*log(pred))
}
ofv <- sum(ofv_kang(pred[!id_like], ...), ofv_likelihood(pred[id_like]))
```
Then, blq can leverage ofv_likelihood and be integrated as a specific case:
```r
pred_blq <- stats::pnorm(idlloq, pred, sqrt(g2), lower.tail = TRUE, log.p = FALSE)
ofv_blq <- ofv_likelihood(pred_blq)
```

From what I understand the likelihood flag would be more flexible for categorical data and allow integration of PD models such as Repeated Time to Event models

**Comment by FelicienLL** [comment]
Yes, we could do something like this. However, I really want to keep BLQ to be treated as an exception where a basic user do not have to code a likelihood function and everything, and can just ask for applying the M3 method as easily as possible. Advanced users who implement complex models as you mentioned should still have the possibility to customize likelihood function. I'll try to think about something as simple as possible but with a syntax as close as possible to NONMEM. 
Useful refs:
* [Bob Bauer CPTPSP tutorial pt 2](https://ascpt.onlinelibrary.wiley.com/doi/10.1002/psp4.12422).

**Comment by FelicienLL** [comment]
Sorry for the late reply, but I did not advanced on this and I doubt I could work on that in the near future. I'm turning this PR into a "LLOQ" feature only for the forthcoming version on the package, and I keep the issue open for a more general M3 method later.

**Comment by pchelle** [comment]
> Sorry for the late reply, but I did not advanced on this and I doubt I could work on that in the near future. I'm turning this PR into a "LLOQ" feature only for the forthcoming version on the package, and I keep the issue open for a more general M3 method later.

No worries. Handling lloq is a great feature.
Thanks again for everything :)

**Pull request merged**
